### ISSUE TITLE
Update to Module#get()

### ISSUE THREAD

**Issue by jshvarts** [rygelouv/LiteKoin#3]
Hi Rygel,

Great work with the article and the sample repo. Looks like the article needs to be updated as following:

From:
```
inline fun <reified T: Any> get(): T {
        val declaration = declarationRegistry[T::class]
        var instance = declaration?.invoke() ?: error("Unable to find declaration of type ${T::class.qualifiedName}")
        return instance as T
 }
```

To something like this?
```
inline fun <reified T: Any> get(): T {
    var instance = KoinLiteContext.getKoinLite().declarations[T::class]?.invoke()
        ?: error("Unable to find declaration of type ${T::class.qualifiedName}")
    return instance as T
}
```

Otherwise an `error` is always thrown as declaration is not found when `get()` is called.

James

**Comment by rygelouv** [comment]
@jshvarts Hey, you are right. Let me update the article. Thank you very much for your feedback. 
I'm a big fan of yours by the way. I read several of your posts on medium 😉
